---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.openshift.io/vcs-uri: <<unknown>>
    app.quarkus.io/quarkus-version: 3.14.4
    app.quarkus.io/commit-id: 85acc117748825c4ab28adeff406fa9dff041637
    app.quarkus.io/vcs-uri: https://gitlab.consulting.redhat.com/2222/uki-sa/demolab/spikes/eda-for-eda.git
    app.quarkus.io/build-timestamp: 2024-09-17 - 16:49:15 +0000
  labels:
    app.kubernetes.io/name: eda-snow-receiver
    app.kubernetes.io/version: 1.0-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
    app.openshift.io/runtime: quarkus
  name: eda-snow-receiver
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: {{ .Values.app.ports.http }}
  selector:
    app.kubernetes.io/name: eda-snow-receiver
    app.kubernetes.io/version: 1.0-SNAPSHOT
  type: ClusterIP
