apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: eda-streams
  namespace: amqstreams
spec:
  kafka:
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      inter.broker.protocol.version: '3.6'
    storage:
      type: persistent-claim
      size: 5Gi
      deleteClaim: true
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: kafka-metrics-config.yml
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
      - name: external
        port: 9094
        tls: true
        type: route
    version: 3.6.0
    replicas: 1
  kafkaExporter:
    groupRegex: ".*"
    groupExcludeRegex: "^excluded-.*"
    topicRegex: ".*"
    topicExcludeRegex: "^excluded-.*"
  entityOperator:
    topicOperator: {}
    userOperator: {}
  zookeeper:
    storage:
      type: persistent-claim
      deleteClaim: true
      size: 5Gi
    replicas: 1