---

- name: create incident in servicenow
  hosts: localhost
  gather_facts: no
  tasks:
  - name: create incident
    servicenow.itsm.incident:
      state: new
      short_description: "{{ ansible_eda.event.body.snow.short_description }}"
      description: "{{ ansible_eda.event.body.snow.description }}"
      impact: low
      urgency: low
      other:
        cmdb_ci: "{{ ansible_eda.event.body.snow.cmdb_ci }}"
    register: incident_number
    retries: 5
    delay: 10
    until: incident_number is not failed

  - name: display incident number
    debug:
       msg: "Incident raised with number - {{ incident_number.record.number }}"
