---

- hosts: "{{ ansible_eda.event.body.entity.metadata.name | default('all') }}"
  gather_facts: false
  pre_tasks:
  - name: assert that we only have one host in the play
    ansible.builtin.assert:
     that:
        - ansible_play_hosts | length <= 1
     fail_msg: 'Should only be one host in the play.'
    run_once: true

  tasks:
  - name: restart application service
    ansible.builtin.systemd:
      name: rest-heroes
      state: started
      scope: user
    become: true
    become_user: heroes
